### ISSUE TITLE
neuralmagic (CPU) model  load tries to run cuda

### ISSUE THREAD

**Issue by veonua** [rom1504/all-clip#11]
```
from all_clip import load_clip

clip_model = "nm:neuralmagic/CLIP-ViT-B-32-256x256-DataComp-s34B-b86K-quant-ds"
use_jit = False
warmup_batch_size = 1
clip_cache_path = "~/repos/laion/"

model, _, _ = load_clip(
            clip_model=clip_model,
            use_jit=use_jit,
            #warmup_batch_size=warmup_batch_size,
            clip_cache_path=clip_cache_path,
        )
```

--> 226 warmup(warmup_batch_size, device, preprocess, model)
--> 143     image = [np.array(image)]

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by rom1504** [comment]
you should `export CUDA_VISIBLE_DEVICES=` to disable cuda / the gpu

**Comment by rom1504** [comment]
or you can pass device="cpu" to load_clip
